# buildarr — read access to arr-stack API keys (Radarr, Prowlarr, Sonarr, Sportarr)
# Generated by D-17-44 (2026-05-03) — Buildarr config-as-code substrate, §18.G component 2.
# Consumer: buildarr container (callum027/buildarr:latest) via Vault Agent sidecar.
# Scope reduced to Radarr + Prowlarr managed instances; Sonarr + Sportarr keys included
# so Prowlarr application records reference live api_keys without hardcoding.

path "secret/data/arr/radarr" {
  capabilities = ["read"]
}

path "secret/data/arr/prowlarr" {
  capabilities = ["read"]
}

path "secret/data/arr/sonarr" {
  capabilities = ["read"]
}

path "secret/data/arr/sportarr" {
  capabilities = ["read"]
}
