# control-plane — operator control plane
# Generated by Block 2.5 P2.1 (2026-04-28)
#
# Read access to operator password hash + Sonarr/Radarr/Prowlarr API
# keys (already provisioned at secret/arr/* by Block 2 homepage work).
# List access to KV metadata for the credentials view (paths only,
# never values). Status reads on Vault sys endpoints. Explicit deny on
# any policy or AppRole modification.

# ── Operator auth ─────────────────────────────────────────────────────
path "secret/data/control-plane/operator" {
  capabilities = ["read"]
}

# ── Service API keys (read-only consumption) ──────────────────────────
path "secret/data/arr/sonarr" {
  capabilities = ["read"]
}

path "secret/data/arr/radarr" {
  capabilities = ["read"]
}

path "secret/data/arr/prowlarr" {
  capabilities = ["read"]
}

# ── Backup snapshot enumeration ───────────────────────────────────────
path "secret/data/restic/backup" {
  capabilities = ["read"]
}

path "secret/data/minio/backup" {
  capabilities = ["read"]
}

# ── KV metadata for credentials browse (hash-only display) ────────────
# secret/metadata/* lists path keys; values live at secret/data/*
# which we do NOT grant here.
path "secret/metadata" {
  capabilities = ["list"]
}

path "secret/metadata/*" {
  capabilities = ["list", "read"]
}

# ── Vault status reads ────────────────────────────────────────────────
path "sys/health" {
  capabilities = ["read"]
}

path "sys/seal-status" {
  capabilities = ["read"]
}

path "sys/policies/acl" {
  capabilities = ["list"]
}

path "sys/policies/acl/+" {
  capabilities = ["read"]
}

path "auth/approle/role" {
  capabilities = ["list"]
}

# ── Explicit deny: policy and AppRole modification ────────────────────
# Deny capabilities supersede any other matching policy block. Belt-and-
# suspenders against accidental escalation if metadata grants ever drift.
path "sys/policies/acl/*" {
  capabilities = ["deny"]
}

path "auth/approle/role/*" {
  capabilities = ["deny"]
}
