# dashboard — read-only access to arr-stack + qnap secrets
# Generated by D-17-38 §A1 (2026-05-03) — closes Gap F5 silence mechanism.
# Consumer: ai-platform-dashboard (bin/selfheal.py via framework/health_checker.py)

path "secret/data/arr/sonarr" {
  capabilities = ["read"]
}

path "secret/data/arr/radarr" {
  capabilities = ["read"]
}

path "secret/data/arr/prowlarr" {
  capabilities = ["read"]
}

path "secret/data/qnap/admin" {
  capabilities = ["read"]
}
