# grafana-obs — read-only access to its own secrets
# Generated by H1 §5 (2026-04-29)
# Block 2 P2.0 (2026-04-28): added admin path for sidecar-rendered admin password

path "secret/data/grafana/api" {
  capabilities = ["read"]
}

path "secret/data/grafana/admin" {
  capabilities = ["read"]
}
