# homeassistant — read-only access to its own secrets
# Generated by H1 §5 (2026-04-29); expanded Block 3 P2.3 (2026-04-28)

# Long-lived bearer token used by Mac Mini-side automation
path "secret/data/homeassistant/api" {
  capabilities = ["read"]
}

# Admin credential — read for autonomous bootstrap (browser onboarding paste)
# and post-onboarding token generation against /auth/token endpoint.
path "secret/data/homeassistant/admin" {
  capabilities = ["read"]
}

# Per-integration credentials populated as integrations are configured
# (Hue, Lutron Caseta, Shelly, Meross, Warmup, etc.)
path "secret/data/homeassistant/integrations/*" {
  capabilities = ["read"]
}
