# homepage — read-only access to its own secrets
# Generated by H1 §5 (2026-04-29)
# Block 2 P2.1 (2026-04-28): added grafana/api, plane/api, opnsense/api for control-center widgets

path "secret/data/homeassistant/api" {
  capabilities = ["read"]
}

path "secret/data/plex/api" {
  capabilities = ["read"]
}

path "secret/data/arr/sonarr" {
  capabilities = ["read"]
}

path "secret/data/arr/radarr" {
  capabilities = ["read"]
}

path "secret/data/arr/prowlarr" {
  capabilities = ["read"]
}

path "secret/data/openweathermap/api" {
  capabilities = ["read"]
}

path "secret/data/grafana/api" {
  capabilities = ["read"]
}

path "secret/data/plane/api" {
  capabilities = ["read"]
}

path "secret/data/opnsense/api" {
  capabilities = ["read"]
}
