# homepage — read-only access to its own secrets
# Generated by H1 §5 (2026-04-29)

path "secret/data/homeassistant/api" {
  capabilities = ["read"]
}

path "secret/data/plex/api" {
  capabilities = ["read"]
}

path "secret/data/arr/sonarr" {
  capabilities = ["read"]
}

path "secret/data/arr/radarr" {
  capabilities = ["read"]
}

path "secret/data/arr/prowlarr" {
  capabilities = ["read"]
}

path "secret/data/openweathermap/api" {
  capabilities = ["read"]
}
