# inventree — parts inventory application policy
# Generated by Phase 13 Increment 2A (2026-04-29)
#
# Single Vault policy attached to a single AppRole consumed by 3
# Vault Agent sidecars (one per credential consumer): inventree app
# (which also covers the worker — same image, same env file),
# inventree-postgres, inventree-redis. Each sidecar renders only its
# consumer's env file but uses the same AppRole token. Read-only on
# consumed secrets; explicit-deny on policy/AppRole modification
# (mirrors the netbox-policy.hcl shape).
#
# Supplier credential paths (secret/data/mouser, secret/data/digikey)
# are added in Increment 2B once those Vault paths exist; explicitly
# omitted from this policy file until then.

# ── Application secrets (read-only consumption) ───────────────────────
path "secret/data/inventree/postgres" {
  capabilities = ["read"]
}

path "secret/data/inventree/redis" {
  capabilities = ["read"]
}

path "secret/data/inventree/secret_key" {
  capabilities = ["read"]
}

path "secret/data/inventree/admin" {
  capabilities = ["read"]
}

# ── API token: read-only ──────────────────────────────────────────────
# Token populated post-bootstrap by the operator script (running with
# the root token). This AppRole only needs read; consumer scripts
# (CSV import in 2B, future cross-index in 4.E) source the token
# from Vault via this same AppRole.
path "secret/data/inventree/api_token" {
  capabilities = ["read"]
}

# ── KV metadata for hash-only display tooling ────────────────────────
path "secret/metadata/inventree" {
  capabilities = ["list"]
}

path "secret/metadata/inventree/*" {
  capabilities = ["list", "read"]
}

# ── Vault status reads ────────────────────────────────────────────────
path "sys/health" {
  capabilities = ["read"]
}

path "sys/seal-status" {
  capabilities = ["read"]
}

# ── Explicit deny: policy and AppRole modification ────────────────────
# Deny capabilities supersede any other matching policy block.
path "sys/policies/acl/*" {
  capabilities = ["deny"]
}

path "auth/approle/role/*" {
  capabilities = ["deny"]
}
