# litellm-gateway — read-only access to its own secrets
# Generated by H1 §5 (2026-04-29)
# Updated H1 §6 A.5 (2026-04-28): removed secret/data/plane/api per Finding 7
# (litellm does not consume PLANE_API_TOKEN; that field belongs to mcpo-proxy)

path "secret/data/anthropic/api" {
  capabilities = ["read"]
}

path "secret/data/openai/api" {
  capabilities = ["read"]
}

path "secret/data/litellm/master" {
  capabilities = ["read"]
}
