# mcpo-proxy — read-only access to its own secrets
# Generated by H1 §6 A.5 (2026-04-28)
# Service: MCP stdio→OpenAPI bridge (Open WebUI tools)
# Consumes: PLANE_API_TOKEN

path "secret/data/plane/api" {
  capabilities = ["read"]
}
