# netbox — CMDB application policy
# Generated by Block 4.C C2.1 (2026-04-29)
#
# Single Vault policy attached to a single AppRole consumed by 4
# Vault Agent sidecars (one per credential consumer): netbox app,
# netbox-postgres, netbox-redis, netbox-redis-cache. Each sidecar
# renders only its consumer's env file but uses the same AppRole
# token. Read-only on consumed secrets; explicit-deny on
# policy/AppRole modification (belt-and-suspenders).

# ── Application secrets (read-only consumption) ───────────────────────
path "secret/data/netbox/app" {
  capabilities = ["read"]
}

path "secret/data/netbox/postgres" {
  capabilities = ["read"]
}

path "secret/data/netbox/redis" {
  capabilities = ["read"]
}

path "secret/data/netbox/redis-cache" {
  capabilities = ["read"]
}

path "secret/data/netbox/secret_key" {
  capabilities = ["read"]
}

path "secret/data/netbox/admin" {
  capabilities = ["read"]
}

# ── API token: read-only ──────────────────────────────────────────────
# Per C2 discovery #5, the API token is provisioned by the operator
# script (running with the root token, not this AppRole) and then
# rendered into credentials.env. The netbox AppRole only needs read.
# Migration scripts (C3) and back-fill scripts (C4) source the token
# from Vault via this same AppRole.
path "secret/data/netbox/api_token" {
  capabilities = ["read"]
}

# ── KV metadata for hash-only display tooling ────────────────────────
# Used by hash-only verification scripts; never exposes values.
path "secret/metadata/netbox" {
  capabilities = ["list"]
}

path "secret/metadata/netbox/*" {
  capabilities = ["list", "read"]
}

# ── Vault status reads ────────────────────────────────────────────────
path "sys/health" {
  capabilities = ["read"]
}

path "sys/seal-status" {
  capabilities = ["read"]
}

# ── Explicit deny: policy and AppRole modification ────────────────────
# Deny capabilities supersede any other matching policy block.
path "sys/policies/acl/*" {
  capabilities = ["deny"]
}

path "auth/approle/role/*" {
  capabilities = ["deny"]
}
