# nextcloud — read-only access to its own secrets
# Generated by H1 §5 (2026-04-29)

path "secret/data/nextcloud/admin" {
  capabilities = ["read"]
}

path "secret/data/nextcloud/db" {
  capabilities = ["read"]
}
