# open-webui — read-only access to its own secrets
# Generated by H1 §5 (2026-04-29)

path "secret/data/open-webui/app" {
  capabilities = ["read"]
}

path "secret/data/litellm/master" {
  capabilities = ["read"]
}
