# openproject — read-only access to its own secrets
# Generated by D-17-04 WP-17-04-01 (2026-05-01)
# Consumer: docker/openproject/ via Vault Agent sidecar
# (replaces plane-api-policy / plane-db-policy / plane-minio-policy
#  pattern when Plane is retired in WP-17-04-06)

path "secret/data/openproject/admin" {
  capabilities = ["read"]
}

path "secret/data/openproject/db" {
  capabilities = ["read"]
}

path "secret/data/openproject/api" {
  capabilities = ["read"]
}

path "secret/data/openproject/secret_key" {
  capabilities = ["read"]
}
