# opnsense-api-reader — read-only access to OPNsense API credentials
# Generated by 17.I T1 (2026-05-01)
# Consumer: scripts/opnsense-client.{py,sh} on Mac Mini, used by
# scripts/check-repo-coherence.py caddy-unbound-parity subcommand
# (drift detection — D-16-06).

path "secret/data/opnsense/api" {
  capabilities = ["read"]
}
