# plane-web — read-only access to its own secrets
# Generated by H1 §5 (2026-04-29)

path "secret/data/plane/admin" {
  capabilities = ["read"]
}

path "secret/data/plane/api" {
  capabilities = ["read"]
}
