# xindex — cross-index service policy
# Generated by D-16-02.1 (2026-05-01)
#
# Single Vault policy attached to a single AppRole consumed by the
# xindex-vault-agent sidecar. The sidecar renders NetBox API token
# into /Users/admin/.vault-agent-secrets/xindex/netbox-credentials.env.
# Read-only on consumed secrets; explicit-deny on policy/AppRole
# modification (belt-and-suspenders).
#
# Scope is intentionally narrow: only NetBox API token in this
# deliverable. D-16-02.2 (Plane source) and future sources extend
# this policy with additional read paths — never broader capabilities.

# ── NetBox API token (read-only consumption) ──────────────────────────
# Same path as scripts/netbox-custom-fields.py reads. Token assembled
# by template as `nbt_{key}.{token}`.
path "secret/data/netbox/api_token" {
  capabilities = ["read"]
}

# ── Vault status reads ────────────────────────────────────────────────
path "sys/health" {
  capabilities = ["read"]
}

path "sys/seal-status" {
  capabilities = ["read"]
}

# ── Explicit deny: policy and AppRole modification ────────────────────
# Deny capabilities supersede any other matching policy block.
path "sys/policies/acl/*" {
  capabilities = ["deny"]
}

path "auth/approle/role/*" {
  capabilities = ["deny"]
}
