# xindex — cross-index service policy
# Generated by D-16-02.1 (2026-05-01)
#
# Single Vault policy attached to a single AppRole consumed by the
# xindex-vault-agent sidecar. The sidecar renders NetBox API token
# into /Users/admin/.vault-agent-secrets/xindex/netbox-credentials.env.
# Read-only on consumed secrets; explicit-deny on policy/AppRole
# modification (belt-and-suspenders).
#
# Scope is intentionally narrow: NetBox + OpenProject (D-17-04
# WP-17-04-05.5; the OpenProject path replaces the prior Plane path
# retired with Plane CE). Future sources extend with additional read
# paths — never broader capabilities.

# ── NetBox API token (read-only consumption) ──────────────────────────
# Same path as scripts/netbox-custom-fields.py reads. Token assembled
# by template as `nbt_{key}.{token}`.
path "secret/data/netbox/api_token" {
  capabilities = ["read"]
}

# ── OpenProject API token (read-only consumption, D-17-04 WP-17-04-05.5) ──
# Same path as scripts/openproject-sync-from-framework.py reads. xindex
# consumes only the `token` field of secret/openproject/api; ADR-A-006
# forbids xindex from writing to OpenProject.
path "secret/data/openproject/api" {
  capabilities = ["read"]
}

# ── Vault status reads ────────────────────────────────────────────────
path "sys/health" {
  capabilities = ["read"]
}

path "sys/seal-status" {
  capabilities = ["read"]
}

# ── Explicit deny: policy and AppRole modification ────────────────────
# Deny capabilities supersede any other matching policy block.
path "sys/policies/acl/*" {
  capabilities = ["deny"]
}

path "auth/approle/role/*" {
  capabilities = ["deny"]
}
