# zabbix-server — read-only access to its own secrets
# Generated by H1 §5 (2026-04-29)

path "secret/data/zabbix/admin" {
  capabilities = ["read"]
}

path "secret/data/zabbix/db" {
  capabilities = ["read"]
}
