from framework.runtime_contract_catalog import RuntimeContractCatalog

def build_runtime_contract_catalog() -> RuntimeContractCatalog:
    return RuntimeContractCatalog(
        session_contracts=sorted(["ExecutionSession", "SessionAuditPlan", "SessionAuditResult", "SessionAuditSummary", "SessionPromptPlan", "SessionPromptResult", "SessionRouteRecord", "SessionWindowAudit", "SessionWindowPlan", "SessionWindowResult"]),
        execution_contracts=sorted(["CompletionRecord", "ExecutionAttempt", "ExecutionAuditTrail", "ExecutionCheckpoint", "ExecutionCompletionSummary", "ExecutionDecision", "ExecutionEnvelope", "ExecutionOutcome", "ExecutionPolicy", "ExecutionRecordPlan", "ExecutionRecordResult", "ExecutionRecordSummary", "ExecutionReport", "ExecutionSnapshot", "ExecutionSnapshotResult", "ExecutionSummary", "ExecutionTracePlan", "ExecutionTraceResult", "ExecutionTraceSummary", "ExecutionWindow", "FailureRecord"]),
        validation_contracts=sorted(["GateAudit", "ValidationFailureSummary", "ValidationGate", "ValidationGateAuditResult", "ValidationGateResult", "ValidationOutcome", "ValidationPlan", "ValidationPlanResult", "ValidationSessionRecord", "ValidationSummary"]),
        artifact_contracts=sorted(["ArtifactIndex", "ArtifactLinkIndex", "ArtifactManifest", "ArtifactPackage", "ArtifactPackageAudit", "ArtifactPackageResult", "ArtifactRecord", "DiffSummary", "FileChangePlan", "FileChangeResult", "FileScopeRecord", "FileTarget", "FileWritePlan", "FileWriteResult", "OutputBundle", "OutputBundleAudit", "OutputBundleResult", "TaskArtifactLink", "WriteIntent"]),
        routing_contracts=sorted(["ApprovalRecord", "CommandPlan", "CommandResult", "ExecutionRouteAudit", "ExecutionRoutePlan", "ExecutionRouteResult", "Job", "PromptEnvelope", "PromptResult", "PromptSegment", "RequestBatch", "RequestBatchAudit", "RequestBatchResult", "RequestContext", "RequestQueue", "RequestQueueAudit", "RequestQueueResult", "RetryPolicy", "ReviewRecord", "ReviewSummary", "RollbackRecord", "RouteAudit", "RouteConstraint", "RoutePlan", "RouteResult", "RouteSelection", "RouteSummary", "RunLedger", "RunManifest", "RunMetrics", "RunRequest", "RunResult", "RunState", "ScopeAuditResult", "ScopeGuard", "ScopeResult", "ToolInvocation", "ToolResult", "WorkspaceSchema"]),
    )
