#!/usr/bin/env bash
# Artifact ingestion — D-17-37 substrate.
#
# Usage:
#   scripts/artifact-ingest.sh <deliverable-id> <local-path> [--class CLASS] [--no-index]
#
# Example:
#   scripts/artifact-ingest.sh D-17-35 /Users/admin/Documents/property/ono-island/source/Cox_V3_…House.pdf --class property
#
# Behavior:
#   1. Verify QNAP mount alive
#   2. Resolve target path: /Users/admin/mnt/qnap-downloads/manual/roadmap-artifacts/<phase>/<deliverable>/source/
#   3. mkdir -p the deliverable subtree (source/, extracted/, annotations/)
#   4. MOVE (not copy) the file in. Set perms per ACL class.
#   5. Emit metadata.yaml stub if absent
#   6. Trigger artifact-axis registry refresh (unless --no-index)
#   7. Print qnap:// pointer to stdout
#
# ACL classes:
#   property      dir 700, files 600  (admin-only)
#   schematics    dir 750, files 640  (per-project)
#   vendor-docs   dir 755, files 644  (read-broadly)
#   source-files  dir 750, files 640  (source dumps)
#
# Exit non-zero on any failure. NEVER copy artifacts via terminal one-off (the
# pattern that triggered D-17-37); always use this script.

set -euo pipefail

ARTIFACT_ROOT="/Users/admin/mnt/qnap-downloads/manual/roadmap-artifacts"
QNAP_URI_PREFIX="qnap://download/manual/roadmap-artifacts"
QNAP_MOUNT_CHECK="/Users/admin/mnt/qnap-downloads"
REFRESH_SH="/Users/admin/repos/integrated-ai-platform/scripts/platform-registry/refresh-artifacts.sh"

usage() {
    cat <<EOF
Usage: $0 <deliverable-id> <local-path> [--class CLASS] [--no-index]

  CLASS : property | schematics | vendor-docs | source-files (default: property)

Example:
  $0 D-17-35 ~/Documents/property/ono-island/source/foo.pdf --class property
EOF
    exit 64
}

if [ "$#" -lt 2 ]; then usage; fi

DELIVERABLE_ID="$1"
LOCAL_PATH="$2"
shift 2

ACL_CLASS="property"
DO_INDEX=1
while [ "$#" -gt 0 ]; do
    case "$1" in
        --class) ACL_CLASS="$2"; shift 2 ;;
        --no-index) DO_INDEX=0; shift ;;
        *) echo "ERROR: unknown flag $1" >&2; usage ;;
    esac
done

# Validate deliverable-id format (D-NN-NN)
if ! echo "$DELIVERABLE_ID" | grep -Eq '^D-[0-9]+-[0-9]+$'; then
    echo "ERROR: deliverable-id must match D-NN-NN (got: $DELIVERABLE_ID)" >&2
    exit 65
fi

# Validate ACL class
case "$ACL_CLASS" in
    property)     DIR_MODE=700; FILE_MODE=600 ;;
    schematics)   DIR_MODE=750; FILE_MODE=640 ;;
    vendor-docs)  DIR_MODE=755; FILE_MODE=644 ;;
    source-files) DIR_MODE=750; FILE_MODE=640 ;;
    *) echo "ERROR: invalid --class $ACL_CLASS (allowed: property|schematics|vendor-docs|source-files)" >&2; exit 65 ;;
esac

# Verify QNAP mount alive
if ! mount | grep -q "$QNAP_MOUNT_CHECK"; then
    echo "ERROR: QNAP not mounted at $QNAP_MOUNT_CHECK" >&2
    echo "  Run: docs/runbooks/qnap-downloads-mount.md" >&2
    exit 66
fi

# Verify source file exists and is readable
if [ ! -f "$LOCAL_PATH" ]; then
    echo "ERROR: local file not found: $LOCAL_PATH" >&2
    exit 67
fi

# Derive phase from deliverable-id (D-17-NN -> phase-17)
PHASE_NUM=$(echo "$DELIVERABLE_ID" | awk -F- '{print $2}')
PHASE_DIR="phase-${PHASE_NUM}"
DELIVERABLE_DIR="$ARTIFACT_ROOT/$PHASE_DIR/$DELIVERABLE_ID"
SOURCE_SUBDIR="$DELIVERABLE_DIR/source"

# Create deliverable subtree
mkdir -p "$DELIVERABLE_DIR/source" "$DELIVERABLE_DIR/extracted" "$DELIVERABLE_DIR/annotations"
# QNAP smbfs mount may reject macOS chmod; try-and-warn.
chmod "$DIR_MODE" "$DELIVERABLE_DIR" "$DELIVERABLE_DIR/source" "$DELIVERABLE_DIR/extracted" "$DELIVERABLE_DIR/annotations" 2>/dev/null || \
    echo "WARN: chmod $DIR_MODE on $DELIVERABLE_DIR rejected by smbfs (QNAP-side ACL governs)" >&2

# Move file in (idempotency: if target exists with same size, skip; else fail rather than overwrite)
BASENAME=$(basename "$LOCAL_PATH")
TARGET="$SOURCE_SUBDIR/$BASENAME"
if [ -e "$TARGET" ]; then
    SRC_SIZE=$(stat -f%z "$LOCAL_PATH" 2>/dev/null || stat -c%s "$LOCAL_PATH")
    DST_SIZE=$(stat -f%z "$TARGET" 2>/dev/null || stat -c%s "$TARGET")
    if [ "$SRC_SIZE" = "$DST_SIZE" ]; then
        echo "INFO: target exists same size; skipping move (idempotent re-ingest)"
        rm -f "$LOCAL_PATH"
    else
        echo "ERROR: target exists with different size ($DST_SIZE vs source $SRC_SIZE): $TARGET" >&2
        echo "       Remove target manually if intentional overwrite is desired." >&2
        exit 68
    fi
else
    mv "$LOCAL_PATH" "$TARGET"
fi
chmod "$FILE_MODE" "$TARGET" 2>/dev/null || \
    echo "WARN: chmod $FILE_MODE on $TARGET rejected by smbfs" >&2

# Emit metadata.yaml stub if absent
META="$DELIVERABLE_DIR/metadata.yaml"
if [ ! -f "$META" ]; then
    cat > "$META" <<EOF
# D-17-37 artifact substrate metadata stub
# Generated by scripts/artifact-ingest.sh
deliverable_id: $DELIVERABLE_ID
phase: $PHASE_DIR
acl_class: $ACL_CLASS
created_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Add operator-locked facts below as the deliverable progresses.
facts: {}
EOF
    chmod "$FILE_MODE" "$META" 2>/dev/null || true
fi

# Build qnap:// pointer
QNAP_PTR="$QNAP_URI_PREFIX/$PHASE_DIR/$DELIVERABLE_ID/source/$BASENAME"

# Refresh registry
if [ "$DO_INDEX" -eq 1 ]; then
    if [ -x "$REFRESH_SH" ]; then
        "$REFRESH_SH" >/dev/null 2>&1 || echo "WARN: artifact registry refresh exited non-zero" >&2
    else
        echo "WARN: $REFRESH_SH not executable; skipping index" >&2
    fi
fi

echo "$QNAP_PTR"
